### ISSUE TITLE
b.deps is not a function

### ISSUE THREAD

**Issue by pravin-d** [pandell/multi-bundle#5]
I trying to use the multi-bundle and getting the following issue
TypeError: b.deps is not a function
    at deps (node_modules/multi-bundle/lib/concatdeps.js:33:30)
    at concatDeps (node_modules/multi-bundle/lib/concatdeps.js:53:12)

Any idea wats going wrong ?

**Comment by jgoz** [comment]
Hi, this project hasn't been touched in several years and was never taken past prototype stage. I would recommend not using it.

I'll update the README to make this clearer.
